services:
  zapache:
    build: .
    ports:
      - '8080:80'
    volumes:
      - ".:/var/www/html"
    links:
      - zmysql
  zmysql:
    image: "mysql:5.7"
    volumes: 
      - /tmp/zmysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
